version: '2'
services:
  web:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
    command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
    restart: always
    volumes:
      - .:/logviewer
    ports:
      - "8081:3000"
