version: '2'

# A Docker Compose file for configuration of the development environment

services:
  web:
    build:
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/logviewer
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_AZURE=${DB_AZURE}
