version: '2'
services:
  web:
    build:
      args:
        - http_proxy
        - https_proxy
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    ports:
      - "8081:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_AZURE=${DB_AZURE}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
