version: '2'

# A Docker Compose file for configuration of the development environment

services:
  web:
    build:
      context: .
    command: bundle exec rails s -e development -p 3000 -b '0.0.0.0'
    volumes:
      - .:/logviewer
    ports:
      - "3000:3000"
