version: '2'
services:
  web:
    build:
      args:
        - http_proxy
        - https_proxy
    restart: always
    ports:
      - "8081:3000"
    environment:
      - RAILS_ENV=production
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_AZURE=${DB_AZURE}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
