# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f6ced5dd8c2b8e2e1c0a96ddac95125bb2f3da2d266daf5e92fb55d68d50fbddbe5fe731c3dedb7097a6c8ec865df48abcbd58b7289a92d1cdc035479c5a0be

test:
  secret_key_base: 455a3bc13361bb3d4c27536e0e64ab2e3989ca4beb43166453cc09ae3a1686011b4e4314eaa492174fa587b7c5743fc231702b1326657c6e1bf1dfa1e9cf2149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
